spring:
  datasource:
    url: jdbc:mysql://47.93.223.78:3306/evalsys
    username: evalsys
    password: ENC(maem9OcXKccpcw167cStI+CtabMNoxJwlRZnx0OmOumGY1DLKNNqsXMn0XeVcnFs)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  data:
    mongodb:
      host: 47.93.223.78
      database: evaldata
      username: evaluser
      password: ENC(maem9OcXKccpcw167cStI+CtabMNoxJwlRZnx0OmOumGY1DLKNNqsXMn0XeVcnFs)
mybatis:
  type-aliases-package: live.bokurano.evalserver.model.mysql
jwt:
  secret: ENC(a/7tcgO+nMg9cFp0Vi4a2uarqfvstuD1AyN4D9uYM/5WN4BxUN/OWOOkDTUpTjIgkVwcZOOKVGvuA1GUAQqeWg==)
  expire: 604800000
